name: Runs on GitHub Action 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-ros:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Simulation
        uses: race-on/simulate@master
      
      - name: Debug
        run: printenv
      
      - uses: actions/upload-artifact@v2
        with:
          name: recorded-messages
#           path: /home/runner/work/_temp/_github_home/.ros/main.bag
          path: /home/runner/work/_temp/_github_home/test
