name: Runs on GitHub Action 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-ros:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker Run
        uses: ./
        
      

#    - name: Install ROS
#      run: bash setup-ros.sh

#    - name: Configure the workspace and lunch the application
#      run: |
#        source /opt/ros/melodic/setup.bash
#        catkin_make
#        source devel/setup.bash
#        timeout 10s roslaunch beginner_tutorials main.launch || exit 0
