name: Runs on GitHub Action 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-ros:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
#       - name: Simulation
#         uses: race-on/simulate@v0.1.2
      
      - name: Debug
        run: printenv
      
      - uses: actions/upload-artifact@v2
        with:
          name: recorded-messages
          path: $HOME/.ros/*.bag
